name: Reusable Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-results.outputs.step-result }}

    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Get build artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}

      - name: List files
        run: ls

      - name: Output information
        run: echo "Deploying & uploading..."

      - name: Set result output
        id: set-results
        run: echo "step-result=success" >> "$GITHUB_OUTPUT"